import json
import math
import time
import os
from typing import Any, Iterable, List, Union
from datetime import datetime
from pathlib import Path

import requests
from pydantic import BaseModel, Field
from dotenv import dotenv_values

import gradio as gr

# LangChain-related imports (kept explicit for clarity)
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain_core.messages import convert_to_openai_messages
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnableLambda
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.embeddings import Embeddings
from langchain_core.documents import Document


# You can use this section to suppress warnings generated by your code:
##def warn(*args, **kwargs):
##    pass
##import warnings
##warnings.warn = warn
##warnings.filterwarnings('ignore')


LOG_FILE = Path(__file__).parent / "output.log"
LOG_LEVEL_NAME = os.getenv("LOG_LEVEL", "DEBUG").upper()


llm_key_location = "C:\\Users\\user\\Desktop\\Coding\\minimax_Key.txt"
llm_model_name = "MiniMax-M3"
llm_model_base_url = "https://api.minimaxi.chat/v1/text/chatcompletion_v2"
embedding_key_location = "C:\\Users\\user\\Desktop\\Coding\\embedding_key.txt"
embedding_model_name = "jina-embeddings-v5-text-nano"
embedding_base_url = "https://api.jina.ai/v1/embeddings"

##################################################################
# Define JSON output structure
class AIResponse(BaseModel):
    summary: str = Field(description="Summary of the user's message")
    sentiment: int = Field(description="Sentiment score from 0 (negative) to 100 (positive)")
    response: str = Field(description="Suggested response to the user")

json_parser = JsonOutputParser(pydantic_object=AIResponse)


def _masked_headers(headers: dict) -> dict:
    masked = dict(headers)
    auth = masked.get("Authorization")
    if isinstance(auth, str) and len(auth) > 12:
        masked["Authorization"] = f"{auth[:10]}...{auth[-4:]}"
    return masked


def _level_num(name: str) -> int:
    return {"DEBUG": 10, "INFO": 20, "WARNING": 30, "ERROR": 40, "CRITICAL": 50}.get((name or "").upper(), 20)


LOG_LEVEL_NUM = _level_num(LOG_LEVEL_NAME)


def set_log_level(level: str) -> None:
    """Set the global log level (e.g. 'DEBUG', 'INFO')."""
    global LOG_LEVEL_NAME, LOG_LEVEL_NUM
    name = (level or "").upper()
    LOG_LEVEL_NAME = name
    LOG_LEVEL_NUM = _level_num(name)


def log(message: Any = "", level: str = "INFO") -> None:
    lvl_name = (level or "").upper()
    if _level_num(lvl_name) < LOG_LEVEL_NUM:
        return
    try:
        if isinstance(message, (dict, list)):
            text = json.dumps(message, ensure_ascii=False)
        else:
            text = str(message)
    except Exception:
        text = repr(message)
    ts = datetime.utcnow().isoformat()
    line = f"{ts} [{lvl_name}] {text}\n"
    try:
        with LOG_FILE.open("a", encoding="utf-8") as f:
            f.write(line)
    except Exception:
        pass
    print(line, end="")


def _load_llm_credentials(key_file: str) -> tuple[str, str]:
    values = dotenv_values(key_file)
    api_key = values.get("MINIMAX_API_KEY")
    group_id = values.get("MINIMAX_GROUP_ID")

    api_key = api_key.strip() if isinstance(api_key, str) else ""
    group_id = group_id.strip() if isinstance(group_id, str) else ""

    if not api_key:
        raise ValueError("MINIMAX_API_KEY is missing or empty.")
    if not group_id:
        raise ValueError("MINIMAX_GROUP_ID is missing or empty.")

    return api_key, group_id


def _llm_runner(prompt_txt: str | Iterable[Any], raise_on_error: bool = True):
    llm_api_key, llm_group_id = _load_llm_credentials(llm_key_location)
    
    log("", "DEBUG")
    log(f"Raw prompt messages: {prompt_txt}", "DEBUG")
    log("", "DEBUG")

    oai_messages = convert_to_openai_messages(prompt_txt, text_format="string")

    if isinstance(oai_messages, dict):
        messages = [oai_messages]
    else:
        messages = oai_messages

    log("", "DEBUG")
    log(f"Converted OpenAI messages: {oai_messages}", "DEBUG")
    log("", "DEBUG")

    # More reliable answer generation with a lower temperature and higher top_p/top_k values
    payload = {
        "model": llm_model_name,
        "messages": messages,
        "max_new_tokens": 256,
        "min_new_tokens": 0,
        "temperature": 0.2,
        "top_p": 0.95,
        "top_k": 40,
    }

    headers = {
        "Authorization": f"Bearer {llm_api_key}",
        "GroupId": llm_group_id,
        "Content-Type": "application/json",
    }

    response = requests.post(llm_model_base_url, headers=headers, json=payload, timeout=120)

    log("", "DEBUG")
    log(f"Response: {response}", "DEBUG")
    log("", "DEBUG")

    parsed = None
    try:
        parsed = response.json()
    except ValueError:
        log("Response body is not valid JSON", "WARNING")

    if raise_on_error:
        response.raise_for_status()

    return parsed if parsed is not None else {"status_code": response.status_code, "text": response.text}


def _format_prompt(variables: dict):
    sys_prompt = variables.get("system_prompt", "")
    usr_prompt = variables.get("user_prompt", "")

    # include JSON format instructions so the model returns structured output
    try:
        format_instructions = json_parser.get_format_instructions()
        full_content = f"{usr_prompt}\n\n{format_instructions}"
    except Exception:
        full_content = usr_prompt

    return [{"role": "system", "content": sys_prompt}, {"role": "user", "content": full_content}]


def invoke_with_prompts(system_p: dict | str, user_p: PromptTemplate):
    """Invoke the runnable chain with given system and user prompts and the country variable.

    Returns the parsed Pydantic object on success, otherwise returns a dict with raw text and raw response.
    """

    chain = RunnableLambda(_format_prompt) | RunnableLambda(_llm_runner)
    
    variables = {"system_prompt": system_p, "user_prompt": user_p}
    resp = chain.invoke(variables)

    # extract assistant text
    if isinstance(resp, dict) and resp.get("choices"):
        try:
            assistant_text = resp["choices"][0]["message"]["content"]
        except Exception:
            assistant_text = json.dumps(resp, ensure_ascii=False)
    else:
        assistant_text = str(resp)

    # try to parse into AIResponse
    try:
        parsed = json_parser.parse(assistant_text)
        return parsed
    except Exception:
        return {"raw_text": assistant_text, "raw_response": resp}


def _load_embedding_credentials(key_file: str) -> tuple[str, str]:
    values = dotenv_values(key_file)
    embedding_key = values.get("EMBEDDING_KEY")
    return embedding_key

embedding_key = _load_embedding_credentials(embedding_key_location)


def _embedding_runner(texts: List[str], url: str = embedding_base_url, api_key: str | None = embedding_key, model: str | None = embedding_model_name, max_retries: int = 5) -> List[List[float]]:
    
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    data = {
        "model": model,
        "task": "retrieval.query",
        "normalized": True,
        "input": texts
    }

    for attempt in range(max_retries):
        try:
            log("", "DEBUG")
            log(f"POST request output for _embedding_runner loop {attempt}:", "DEBUG")
            log("", "DEBUG")
            log("POST request variables for _embedding_runner:", "DEBUG")
            log(f"URL: {url}", "DEBUG")
            log(f"Headers (masked): {json.dumps(_masked_headers(headers), indent=2)}", "DEBUG")
            log(f"JSON payload: {json.dumps(data, indent=2, ensure_ascii=False)}", "DEBUG")
            log("", "DEBUG")

            resp = requests.post(url, headers=headers, data=json.dumps(data), timeout=120)
        except requests.RequestException:
            time.sleep(2** attempt)
            continue

        # Convert response to JSON if possible and handle rate limiting or specific error codes
        try:
            j = resp.json()
        except ValueError:
            j = None

        if resp.status_code == 429:
            time.sleep(2 ** attempt)
            continue
        if isinstance(j, dict) and j.get("base_resp", {}).get("status_code") == 1002:
            time.sleep(2 ** attempt)
            continue

        # Check if the response contains the expected structure for embeddings, a list of lists of floats
        if isinstance(j, dict):
            vectors = _parse_fromDict_toList(j)
            log("", "DEBUG")
            log(f"List Output (dict_to_list): {vectors}", "DEBUG")
            log("", "DEBUG")
            return vectors

        if isinstance(j, list) and all(isinstance(v, list) for v in j):
            log("", "DEBUG")
            log(f"List Output (list): {j}", "DEBUG")
            log("", "DEBUG")
            return j

        time.sleep(2 ** attempt)

    raise RuntimeError(f"Failed to obtain embeddings from API after {max_retries} retries")


def _parse_fromDict_toList(j: dict) -> List[List[float]]:
    if isinstance(j, dict):
        if "vectors" in j and isinstance(j["vectors"], list):
            log("", "DEBUG")
            log(f"Found 'vectors' key in response: {j['vectors']}", "DEBUG")
            log("", "DEBUG")
            return j["vectors"]
        if "data" in j and isinstance(j["data"], list):
            out = []
            log("", "DEBUG")
            log(f"Found 'data' key in response: {j}", "DEBUG")
            log("", "DEBUG")
            for item in j["data"]:
                if isinstance(item, dict):
                    for key in ("embedding", "vector"):
                        if key in item and isinstance(item[key], list):
                            out.append(item[key])
                            log("", "DEBUG")
                            log(f"Found '{key}' key in response: {item[key]}", "DEBUG")
                            log("", "DEBUG")
                            break
            if out:
                return out
        if "embeddings" in j and isinstance(j["embeddings"], list):
            log("", "DEBUG")
            log(f"Found 'embeddings' key in response: {j['embeddings']}", "DEBUG")
            log("", "DEBUG")
            return j["embeddings"]
    return []


## Document loader
def _document_loader(file):
    loader = PyPDFLoader(file.name)
    loaded_document = loader.load()
    return loaded_document


## Text splitter
def _text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=50,
        length_function=len,
    )
    chunks = text_splitter.split_documents(data)
    return chunks


def _cosine_similarity(a: List[float], b: List[float]) -> float:
    if a is None or b is None:
        return -1.0
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(y * y for y in b))
    if norm_a == 0 or norm_b == 0:
        return -1.0
    return dot / (norm_a * norm_b)


def _retrieve_top_k(query: str, embedding_index: List[dict], k: int = 4) -> List[str]:
    q_vecs = _embedding_runner([query])
    if not q_vecs:
        return []
    qv = q_vecs[0]
    scores = []
    for item in embedding_index:
        emb = item.get("embedding")
        score = _cosine_similarity(qv, emb)
        scores.append((score, item.get("text")))
    scores.sort(key=lambda x: x[0], reverse=True)
    return [text for _, text in scores[:k]]


## QA Chain
def retriever_qa(file, query):
    # Attempt to use LangChain's RetrievalQA if available; otherwise fallback to a
    # simple retrieval + prompt to the existing LLM runner.
    log("", "INFO")
    log(f"File: {file.name}", "INFO")
    log(f"Query: {query}", "INFO")
    log("", "INFO")
    # Use local similarity search via embeddings and _retrieve_top_k
    try:
        # load document chunks directly from file
        splits = _document_loader(file)
        chunks = _text_splitter(splits)

        # Build a simple embedding index: list of {embedding, text}
        log(f"Building embedding index from {len(chunks)} chunks", "DEBUG")
        embedding_index: List[dict] = []
        texts = []
        for i, d in enumerate(chunks):
            if hasattr(d, "page_content"):
                t = d.page_content
            elif isinstance(d, dict) and d.get("page_content"):
                t = d.get("page_content")
            else:
                t = str(d)
            texts.append(t)
            preview = (t[:200] + "...") if len(t) > 200 else t
            log(f"Chunk {i}: preview={preview!s}", "DEBUG")

        for i, t in enumerate(texts):
            log(f"Embedding chunk {i} (len={len(t)})", "DEBUG")
            vecs = _embedding_runner([t])
            if vecs:
                emb = vecs[0]
                embedding_index.append({"embedding": emb, "text": t})
                try:
                    log(f"Chunk {i} embedding length={len(emb)}", "DEBUG")
                except Exception:
                    log(f"Chunk {i} embedding obtained", "DEBUG")
            else:
                log(f"Chunk {i} embedding empty or failed", "WARNING")

        log(f"Built embedding_index with {len(embedding_index)} entries", "DEBUG")

        top_texts = _retrieve_top_k(query, embedding_index, k=4)
        if top_texts:
            context = "\n\n".join(top_texts)
            prompt = f"Use the following context to answer the question. Context:\n{context}\n\nQuestion: {query}\nAnswer concisely."
            resp = _llm_runner(prompt, raise_on_error=False)

            if isinstance(resp, dict) and resp.get("choices"):
                try:
                    log("", "DEBUG")
                    log(f"LLM response: {json.dumps(resp, indent=2,ensure_ascii=False)}", "DEBUG")
                    log("", "DEBUG")
                    log(f"LLM response result: {resp["choices"][0]["message"]["content"]}", "DEBUG")
                    return resp["choices"][0]["message"]["content"]
                except Exception:
                    return json.dumps(resp, indent=2, ensure_ascii=False)

            return str(resp)
    except Exception:
        log("Embedding-based similarity retrieval failed; falling back to retriever.", "WARNING")


##################################################################
# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"),  # Drag and drop file upload
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Output"),
    title="RAG Chatbot",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)


# Launch the app
rag_application.launch(server_name="0.0.0.0", server_port=7861)

